### ISSUE TITLE
No tx hash after transfer asset

### ISSUE THREAD

**Issue by tevin-maxwell** [soramitsu/iroha-helpers#18]
When transfer assets with Iroha-cli, you would get a tx hash to check the status of the transaction. But transferring assets with iroha-helpers, I would get undefined.

I'm fairly new to this and require some guidance.

**Comment by Pobepto** [comment]
Hi, @tevin-maxwell! Do you need hash of transaction or you just want to check current status?

**Comment by tevin-maxwell** [comment]
Thanks for replying @Pobepto . I would like to check the status of the transaction but don't you need the transaction hash to check the status?

**Comment by Pobepto** [comment]
In our implementation we subscribe to status stream on sending transactions. 

Every command or query is a promise, so if you want to do something on `COMMITTED` status, you can perform it in `then` section, if there will be any errors `catch` will handle it.
``` javascript
commands.transferAsset({
  privateKeys: [privateKey],
  creatorAccountId: 'alice@iroha',
  quorum: 1,
  commandService,
  timeoutLimit: 5000
}, {
  srcAccountId: 'alice@iroha', 
  destAccountId: 'bob@iroha', 
  assetId: 'asset#domain',
  description: 'Test message',
  amount: '1'
})
  .then(res => console.log(res))
  .catch(err => console.log(err))
```

**Comment by tevin-maxwell** [comment]
So when the transaction is `COMMITTED` and both account's assets are adjusted accordingly, the `then` will call?

**Comment by Pobepto** [comment]
Yea, you're right 🙂

**Comment by tevin-maxwell** [comment]
I guess we can close this issue then. Thanks for your help :)

**Comment by tevin-maxwell** [comment]
Not sure if this is a bug, but we discussed that the `then` block would be called when the transaction is `COMMITTED`. This is true when `Quorum` is set to 1. During testing with pending transaction, I noticed that the `then` didn't call at all.

**Comment by Pobepto** [comment]
> Not sure if this is a bug, but we discussed that the `then` block would be called when the transaction is `COMMITTED`. This is true when `Quorum` is set to 1. During testing with pending transaction, I noticed that the `then` didn't call at all.

``` javascript
console.log("===> Sending Transaction");
txUtil.sendTransactions([copyTx], commandService, 5000, ['MST_PENDING']);
```
By default `sentTransactions` method is waiting for `COMMITTED` status from iroha. You can pass an array of expected statuses to `sendTransactions` method, in your case it is `MST_PENDING`

**Comment by tevin-maxwell** [comment]
That means using `transferAsset` function will not work in this scenario and we have to form a new transaction and send them with `MST_PENDING` params

**Comment by Pobepto** [comment]
> That means using `transferAsset` function will not work in this scenario and we have to form a new transaction and send them with `MST_PENDING` params

Unfortunately, it is the only one way to work with `MST_PENDING` right now. In new release we will have feature to create batch without this magic

**Comment by tevin-maxwell** [comment]
looking forward to the new release 😄
