### ISSUE TITLE
Unable to GrantPermission 

### ISSUE THREAD

**Issue by tevin-maxwell** [soramitsu/iroha-helpers#20]
I have userA with permission `can_grant_can_add_my_signatory`. when i tried granting userB with permission `can_add_my_signatory`, i received the following error.
![image](https://user-images.githubusercontent.com/46663993/60083562-254d7a80-9760-11e9-8c24-b791576bb54a.png)

I'm using Iroha-helpers with an Express app as a backend and using Postman to call the function. I do this after failing to grant permission using Iroha-cli.

The environment i'm using are:
- "express": "~4.16.0"
- "iroha-helpers": "^0.6.19"
- "grpc": "^1.21.1"

**Comment by Pobepto** [comment]
@tevin-maxwell Hi! Looks like a bug in our library, I will look at this today 🙂

**Comment by Pobepto** [comment]
Oh, there was an error in key. The newest version will be in `iroha-helpers@0.6.21`. I will release it in few minutes.

Example
``` javascript
import RolePermission from '../lib/proto/primitive_pb'

commands.grantPermission({
  privateKeys: [adminPriv],
  creatorAccountId: 'test@admin',
  quorum: 1,
  commandService,
  timeoutLimit: 5000
}, {
  accountId: 'test@admin',
  permission: RolePermission['CAN_GET_MY_ACCOUNT']
})
```

**Comment by tevin-maxwell** [comment]
It works 😃 thanks for the support.
