### ISSUE TITLE
How to sign a pending transaction?

### ISSUE THREAD

**Issue by tevin-maxwell** [soramitsu/iroha-helpers#22]
I have an account that has 2 `Signatories` with `Quorum` set to `2`. After making a `TransferAsset` transaction with one of the key. The transaction is currently `Pending`. 

Upon looking at the example from python library. I simply need to queries for the pending transaction and sign with the other key and send it.
![Screen Shot 2019-06-28 at 3 07 30 PM](https://user-images.githubusercontent.com/46663993/60327624-925a4d80-99b6-11e9-9f05-375585b8dcec.png)

What i tried with this library was:
- Query and Got the pending transaction
- use `txHelper.addMeta` and `txHelper.sign`
- Then use `sendTransactions` to commit

But it gives error at the `txHelper.addMeta` with `TypeError: a.hasPayload is not a function`.

Could someone guide me on how i could sign a pending transaction?

**Comment by Pobepto** [comment]
@tevin-maxwell Hi! You're almost right. First of all you need to call `getPendingTransactions` to get all pending transactions. Then find needed transaction and sign it with private keys.

It should looks like this
``` javascript
import {
  signWithArrayOfKeys,
  sendTransactions
} from 'iroha-helpers'
import {
  CommandService_v1Client as CommandService
} from 'iroha-helpers/lib/proto/endpoint_pb_service'

function signPendingTransaction (transaction, privateKeys) {
  // cloneDeep is a function from the Lodash library
  let copyTx = cloneDeep(transaction)
  copyTx.clearSignaturesList()
  
  copyTx = signWithArrayOfKeys(copyTx, privateKeys)
  
  return sendTransactions([txToSend], new CommandService(URL), 5000)
}
```

**Comment by tevin-maxwell** [comment]
I assumed the `copyTx.clearSignaturesList()` part is deleting the `signaturesList` field from the object. Is that correct?

The `copyTx = signWithArrayOfKeys(copyTx, privateKeys)` part means you have to sign the transactions with both private keys or just the missing key?

**Comment by tevin-maxwell** [comment]
It would appeared that the `signWithArrayOfKeys` is expecting an object of Transaction Class. While the responses that got from `getPendingTransaction` are plain object.

**Comment by Pobepto** [comment]
> I assumed the copyTx.clearSignaturesList() part is deleting the signaturesList field from the object. Is that correct?

Yea, right. You can see same line in your python code `del tx.signatures[:]`

> The copyTx = signWithArrayOfKeys(copyTx, privateKeys) part means you have to sign the transactions with both private keys or just the missing key?

I don't remember exactly, but I guess you should add only missing one. If I'm wrong, please inform me.

> It would appeared that the `signWithArrayOfKeys` is expecting an object of Transaction Class. While the responses that got from `getPendingTransaction` are plain object.

You should convert it to object using `.toObject()` method.

**Comment by Pobepto** [comment]
I hope we will improve our documentation for library soon :)
Currently we're working on typescript version of library and adding new features like multiple commands in one transaction. I hope we will release it soon, on this week maybe

**Comment by tevin-maxwell** [comment]
here is what I've written

```javascript
console.log("===> Retrieve All Pending Transactions");
const response = await queries.getPendingTransactions(
      createQueryOption(keys[req.headers.key], req.headers.username),
      {}
);

console.log("===> Got first Pending Transaction");
const txPending = response[0];

console.log("===> Signing Transaction");
let copyTx = sign(txPending, keys[req.headers.key]);

console.log("===> Clear Signature List");
copy.Tx.clearSignaturesList();

console.log("===> Sending Transaction");
txUtil.sendTransactions([copyTx], commandService, 5000);
```

I think i'm missing the part where I have to transform the transaction that i got from `getPendingTransaction` info a `Transaction` object. Both `sign` or `signWithArrayOfKeys` expect an object of class `Transaction`

> You should convert it to object using .toObject() method.

This doesn't work as well lol as the response from `getPendingTransaction` are already plain JSON object.

> I hope we will improve our documentation for library soon :)
Currently we're working on typescript version of library and adding new features like multiple commands in one transaction. I hope we will release it soon, on this week maybe

That would be great 😄 I was also looking for batch transaction.

**Comment by Pobepto** [comment]
> I think i'm missing the part where I have to transform the transaction that i got from getPendingTransaction info a Transaction object. Both sign or signWithArrayOfKeys expect an object of class Transaction

You're totally right, I have missed important part! Can you use `getRawPendingTransaction` method? It should return array of raw transactions. So this raw transaction can be used for `sign` and another methods.

Method `.toObject()` uses for converting from raw transaction to plain JSON object, as you already understand 😄

**Comment by tevin-maxwell** [comment]
So after I use `getRawPendingTransaction`, the response data has become unreadable 😅 with `wrappers_` build on top of `wrappers_`. I don't exactly know how to get the object of the transaction now. Any advice you could give me?

**Comment by Pobepto** [comment]
In one of your project we're using such code - `rawPendingTransactions.getTransactionsList()[txId]`. This line should return you a pending transaction by id

**Comment by tevin-maxwell** [comment]
Thanks you 😄 It worked! To confirm, you only need to sign the missing key to finish the transaction. No need to `clearSignaturesList()`

**Comment by Pobepto** [comment]
> No need to clearSignaturesList()

The reason to clear is a correct MST update. Without it you will had long delay before all nodes will update their status of this transaction

Currently it is simple fix for MST update it, but it will fixed with next iroha update, I guess

**Comment by tevin-maxwell** [comment]
So I ran into another issue with signing a pending Transaction with a custom `transferAsset` function with params `MST_PENDING`. The problem is after I signed the transaction with the other key, the transaction was not removed from the pending list from `getPendingTransaction`. The asset was properly adjusted so that means the transfer was a success. 

Here is the function is what i wrote:
```javascript
async function customTransferAsset(req, res){

 // Create Payload
 const payload = {
      srcAccountId: req.body.from,
      destAccountId: `${req.body.to}`,
      assetId: req.body.asset,
      description: req.body.description,
      amount: req.body.amount.toString()
 };

 // Create Command
 const txCommand = addCommand(
      emptyTransaction(),
      "transferAsset",
      validate.default(payload, [
        "srcAccountId",
        "destAccountId",
        "assetId",
        "description",
        "amount"
      ])
 );

 // Create EmptyTx with created Command
 var txToSend = addMeta(txCommand, {
      creatorAccountId: req.headers.username,
      quorum: req.headers.quorum
 });

 // Sign the Transaction with key
 txToSend = txUtil.signWithArrayOfKeys(txToSend, [keys[req.headers.key]]);

 // Send Transaction
 await txUtil.sendTransactions([txToSend], commandService, 5000, ["MST_PENDING"]);
}

```
Of course, i tried with the usual `transferAsset` and it worked just fine. So i assume there is no problem with `sign` function.
I also tried changing the `MST_PENDING` back to `COMMITTED`. I still ran into the same issue.

**Comment by Pobepto** [comment]
Did you try to use `clearSignaturesList`?

**Comment by tevin-maxwell** [comment]
Yes, I also added `clearSignaturesList` but the list is not cleared.

**Comment by Pobepto** [comment]
So, as I understand you clean the signatures list and then using second key to sign the transaction

```javascript
txToSend.clearSignaturesList()
txToSend = txUtil.signWithArrayOfKeys(txToSend, [keys[req.headers.key]])
```

After that the transaction still in `getPendingTransactions`, am I right?

**Comment by tevin-maxwell** [comment]
Yes. Here is the `sign` code:

```javascript
async function signTransaction(req, res){
 const readablePendingTx = await queries.getPendingTransactions(
      createQueryOption(keys[req.headers.key], req.headers.user),
      {}
    );

 console.log("PendingTxFound: ", readablePendingTx.length);

 const matchTxIndex = findIndex(readablePendingTx, tx =>find(tx.signaturesList, signature => 
    signature.publicKey === req.headers.publicKey)
 );

 const response = await queries.getRawPendingTransactions(
      createQueryOption(keys[req.headers.key], req.headers.user),
      {}
 );

 const txPending = response.getTransactionsList()[matchTxIndex];
 txPending.clearSignaturesList();

 let copyTx = sign(txPending, keys[req.headers.key]);
 txUtil.sendTransactions([copyTx], commandService, 5000 );
}
```

To make sure everything works, I also tried deleting and creating new Iroha nodes. The problem still persist.

**Comment by Pobepto** [comment]
@tevin-maxwell So you have more than one peers in network? Ok, I guess this is same problem that we faced in our project. Currently we're waiting for fix in iroha.

Can you try to do it with python library? If it will work there, it means problem in js library 😱

**Comment by tevin-maxwell** [comment]
Yup, I have more than one peers in the network. I'm not proficient in python but ill give it a go 😄 Although, I highly suspect that it's my code that is the problem.

`await txUtil.sendTransactions([txToSend], commandService, 5000, ["MST_PENDING"])`
I remember i tried with only `COMMITTED` params and still receive the same problem but using `transferAsset` function, it works just fine.
