### ISSUE TITLE
domainPattern - validation/check.ts

### ISSUE THREAD

**Issue by diva-exchange** [soramitsu/iroha-helpers#38]
According to the [docs](https://iroha.readthedocs.io/en/latest/develop/api/commands.html#create-domain) the domainId should be validated against RFC1035, RFC1123. 

But [validation/check.ts](https://github.com/soramitsu/iroha-helpers/blob/master/src/validation/checks.ts) validates against
`/^[a-z_0-9]{1,9}$/`

This is also not inline with [Iroha master, field_validator.cpp](https://github.com/hyperledger/iroha/blob/master/shared_model/validators/field_validator.cpp) which validates the domainId against
```
const RegexValidator kDomainValidator{
      "Domain",
      R"#(([a-zA-Z]([a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])?\.)*)#"
      R"#([a-zA-Z]([a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])?)#"};
```
I suggest a relaxed regex within check.ts, like
`/^([a-zA-Z]([a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])?\.)*[a-zA-Z]([a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])?$/`

What are your thoughts on this?

**Comment by Pobepto** [comment]
Hi! Fixed in #43 
Version of iroha-helpers - 0.8.9
